version: '3.8'

services:
  # ============= BACKEND API =============
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seniors_backend
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=sqlite:///./data/database.db
      # ✅ NUEVO: Variables específicas para Docling optimizado
      - DOCLING_CACHE_DIR=/root/.cache/docling
      - OPENCV_OPENCL_DEVICE=disabled
      - OMP_NUM_THREADS=2
      # ✅ NUEVO: Optimizaciones de memoria
      - MALLOC_TRIM_THRESHOLD_=131072
      - MALLOC_MMAP_THRESHOLD_=131072
    volumes:
      - ./data:/app/data
      - ./backend/api/data/uploads:/app/backend/api/data/uploads
      - docling-cache:/root/.cache/docling
      # ✅ NUEVO: Cache de HuggingFace persistente
      - huggingface-cache:/root/.cache/huggingface
    restart: unless-stopped
    networks:
      - proxy
    # ✅ NUEVO: Límites de recursos específicos para Docling
    deploy:
      resources:
        limits:
          memory: 4G        # Docling necesita mucha memoria
          cpus: '2'
        reservations:
          memory: 1.5G        # Mínimo garantizado
          cpus: '1'
    # ✅ MEJORADO: Healthcheck más permisivo para Docling
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health || exit 1"]
      interval: 180s       # Más tiempo entre checks
      timeout: 90s         # Timeout más largo
      retries: 3
      start_period: 180s    # Más tiempo para que Docling se inicie
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.seniors-api.rule=Host(`seniors.horacioai.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.seniors-api.entrypoints=websecure"
      - "traefik.http.routers.seniors-api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.seniors-api.priority=100"
      - "traefik.http.services.seniors-api.loadbalancer.server.port=8000"
      # ✅ NUEVO: Timeouts extendidos para procesamiento PDF largo
      - "traefik.http.services.seniors-api.loadbalancer.server.timeout=600s"
      - "traefik.http.routers.seniors-api.timeout=600s"
      # ✅ NUEVO: Configuración adicional de Traefik para requests grandes
      - "traefik.http.middlewares.seniors-api-buffering.buffering.maxRequestBodyBytes=52428800"
      - "traefik.http.routers.seniors-api.middlewares=seniors-api-buffering"

  # ============= FRONTEND NEXT.JS =============
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: seniors_frontend
    environment:
      - NEXT_PUBLIC_API_URL=https://seniors.horacioai.com/api
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - proxy
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1'
        reservations:
          memory: 512M
          cpus: '0.5'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.seniors.rule=Host(`seniors.horacioai.com`)"
      - "traefik.http.routers.seniors.entrypoints=websecure"
      - "traefik.http.routers.seniors.tls.certresolver=letsencrypt"
      - "traefik.http.routers.seniors.priority=50"
      - "traefik.http.services.seniors.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.seniors-api-buffering.buffering.maxRequestBodyBytes=52428800"
      - "traefik.http.routers.seniors-api.middlewares=seniors-api-buffering"

# ============= VOLÚMENES =============
volumes:
  docling-cache:
    driver: local
  # ✅ NUEVO: Cache persistente para modelos de HuggingFace
  huggingface-cache:
    driver: local

# ============= REDES =============
networks:
  proxy:
    external: true