# docker-compose.yml

# =============================================================================
# PROYECTO EVENTOS MAYORES - Docker Compose Simplificado para Hetzner
# =============================================================================

version: '3.8'

services:
  # ============= BACKEND API =============
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eventos_backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=sqlite:///./data/database.db
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - eventos_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ============= FRONTEND NEXT.JS =============
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: eventos_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - eventos_network

  # ============= NGINX (Reverse Proxy) =============
  nginx:
    image: nginx:alpine
    container_name: eventos_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    networks:
      - eventos_network

# ============= VOLÚMENES =============
volumes:
  eventos_data:

# ============= REDES =============
networks:
  eventos_network:
    driver: bridge

# =============================================================================
# COMANDOS ÚTILES:
#
# Producción:
# docker-compose up -d
#
# Ver logs:
# docker-compose logs -f backend
#
# Rebuild:
# docker-compose build --no-cache
#
# Cleanup:
# docker-compose down -v
# =============================================================================