# docker-compose.yml

version: '3.8'

services:
  # ============= BACKEND API =============
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seniors_backend
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=sqlite:///./data/database.db
    volumes:
      - ./data:/app/data
      - ./backend/api/data/uploads:/app/backend/api/data/uploads
    restart: unless-stopped
    networks:
      - proxy
    # ✅ AÑADIDO: Límites de memoria y recursos
    deploy:
      resources:
        limits:
          memory: 800M          # Máximo 800MB (mata el contenedor si excede)
          cpus: '1.0'           # Máximo 1 CPU
        reservations:
          memory: 200M          # Memoria reservada mínima
          cpus: '0.5'           # CPU reservada mínima
    # ✅ AÑADIDO: Health check para restart automático
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health || exit 1"]
      interval: 60s             # Cada 60 segundos
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.seniors-api.rule=Host(`seniors.horacioai.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.seniors-api.entrypoints=websecure"
      - "traefik.http.routers.seniors-api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.seniors-api.priority=100"
      - "traefik.http.services.seniors-api.loadbalancer.server.port=8000"

  # ============= FRONTEND NEXT.JS =============
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: seniors_frontend
    environment:
      - NEXT_PUBLIC_API_URL=https://seniors.horacioai.com/api
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - proxy
    # ✅ AÑADIDO: Límites más ligeros para frontend
    deploy:
      resources:
        limits:
          memory: 512M          # Frontend necesita menos memoria
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.1'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.seniors.rule=Host(`seniors.horacioai.com`)"
      - "traefik.http.routers.seniors.entrypoints=websecure"
      - "traefik.http.routers.seniors.tls.certresolver=letsencrypt"
      - "traefik.http.routers.seniors.priority=50"
      - "traefik.http.services.seniors.loadbalancer.server.port=3000"

# ============= REDES =============
networks:
  proxy:
    external: true