# docker-compose.yml

version: '3.8'

services:
  # ============= BACKEND API =============
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seniors_backend
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=sqlite:///./data/database.db
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.seniors-api.rule=Host(`seniors.horacioai.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.seniors-api.entrypoints=websecure"
      - "traefik.http.routers.seniors-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.seniors-api.loadbalancer.server.port=8000"

  # ============= FRONTEND NEXT.JS =============
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: seniors_frontend
    environment:
      - NEXT_PUBLIC_API_URL=https://seniors.horacioai.com/api
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.seniors.rule=Host(`seniors.horacioai.com`)"
      - "traefik.http.routers.seniors.entrypoints=websecure"
      - "traefik.http.routers.seniors.tls.certresolver=letsencrypt"
      - "traefik.http.services.seniors.loadbalancer.server.port=3000"

# ============= REDES =============
networks:
  proxy:
    external: true